import type { Account } from "./types";

// Hand-tuned so default scoring yields: 5 HOT, 6 WARM, 5 COLD, 4 NOT READY
// >=4 with renewal < 60 days, >=3 with endOfLife && cloudStatus === "none".
export const MOCK_ACCOUNTS: Account[] = [
  // ---------- HOT (5) ----------
  {
    id: "acc-01",
    accountName: "Meridian Financial Group",
    salesRep: "Alex Chen",
    industry: "Finance",
    region: "East",
    companySize: "12,000 employees",
    deviceModel: "FAS8200",
    deviceAgeYears: 6.2,
    endOfLife: true,
    storageCapacityTB: 480,
    utilizationPct: 88,
    itBudgetUSD: 1_200_000,
    cloudStatus: "hybrid",
    contractRenewalDays: 22,
    annualRevenue: 4_800_000_000,
    lastContactDate: "2026-05-18",
    pipelineStage: "contacted",
  },
  {
    id: "acc-02",
    accountName: "Crestline Health Systems",
    salesRep: "Priya Shah",
    industry: "Healthcare",
    region: "Central",
    companySize: "28,000 employees",
    deviceModel: "AFF A400",
    deviceAgeYears: 5.4,
    endOfLife: true,
    storageCapacityTB: 720,
    utilizationPct: 84,
    itBudgetUSD: 950_000,
    cloudStatus: "active_cloud",
    contractRenewalDays: 41,
    annualRevenue: 6_200_000_000,
    lastContactDate: "2026-05-22",
    pipelineStage: "meeting_scheduled",
  },
  {
    id: "acc-03",
    accountName: "Northwind Cloud Labs",
    salesRep: "Jordan Reyes",
    industry: "Tech",
    region: "West",
    companySize: "3,400 employees",
    deviceModel: "AFF A800",
    deviceAgeYears: 5.8,
    endOfLife: false,
    storageCapacityTB: 920,
    utilizationPct: 91,
    itBudgetUSD: 760_000,
    cloudStatus: "active_cloud",
    contractRenewalDays: 55,
    annualRevenue: 1_400_000_000,
    lastContactDate: "2026-05-26",
    pipelineStage: "proposal_sent",
  },
  {
    id: "acc-04",
    accountName: "Atlas Pharmaceuticals",
    salesRep: "Priya Shah",
    industry: "Healthcare",
    region: "EMEA",
    companySize: "18,500 employees",
    deviceModel: "FAS9000",
    deviceAgeYears: 6.8,
    endOfLife: true,
    storageCapacityTB: 1100,
    utilizationPct: 82,
    itBudgetUSD: 1_500_000,
    cloudStatus: "hybrid",
    contractRenewalDays: 88,
    annualRevenue: 9_200_000_000,
    lastContactDate: null,
    pipelineStage: "not_contacted",
  },
  {
    id: "acc-05",
    accountName: "Sapphire Trust Bank",
    salesRep: "Alex Chen",
    industry: "Finance",
    region: "East",
    companySize: "9,800 employees",
    deviceModel: "AFF C400",
    deviceAgeYears: 4.1,
    endOfLife: false,
    storageCapacityTB: 540,
    utilizationPct: 86,
    itBudgetUSD: 880_000,
    cloudStatus: "active_cloud",
    contractRenewalDays: 28,
    annualRevenue: 3_100_000_000,
    lastContactDate: "2026-05-12",
    pipelineStage: "contacted",
  },

  // ---------- WARM (6) ----------
  {
    id: "acc-06",
    accountName: "Pioneer Manufacturing Co.",
    salesRep: "Marcus Wright",
    industry: "Manufacturing",
    region: "Central",
    companySize: "6,200 employees",
    deviceModel: "FAS2750",
    deviceAgeYears: 5.6,
    endOfLife: true,
    storageCapacityTB: 320,
    utilizationPct: 74,
    itBudgetUSD: 420_000,
    cloudStatus: "licensed_not_deployed",
    contractRenewalDays: 47,
    annualRevenue: 1_800_000_000,
    lastContactDate: "2026-04-30",
    pipelineStage: "contacted",
  },
  {
    id: "acc-07",
    accountName: "Vector Retail Brands",
    salesRep: "Sofia Ramos",
    industry: "Retail",
    region: "West",
    companySize: "14,000 employees",
    deviceModel: "AFF A250",
    deviceAgeYears: 3.6,
    endOfLife: false,
    storageCapacityTB: 280,
    utilizationPct: 55,
    itBudgetUSD: 360_000,
    cloudStatus: "active_cloud",
    contractRenewalDays: 110,
    annualRevenue: 2_200_000_000,
    lastContactDate: "2026-05-08",
    pipelineStage: "meeting_scheduled",
  },
  {
    id: "acc-08",
    accountName: "Helix Biotech",
    salesRep: "Priya Shah",
    industry: "Healthcare",
    region: "West",
    companySize: "2,100 employees",
    deviceModel: "FAS8300",
    deviceAgeYears: 4.4,
    endOfLife: false,
    storageCapacityTB: 410,
    utilizationPct: 66,
    itBudgetUSD: 310_000,
    cloudStatus: "hybrid",
    contractRenewalDays: 140,
    annualRevenue: 780_000_000,
    lastContactDate: "2026-04-15",
    pipelineStage: "contacted",
  },
  {
    id: "acc-09",
    accountName: "Beacon State Bank",
    salesRep: "Alex Chen",
    industry: "Finance",
    region: "Central",
    companySize: "4,500 employees",
    deviceModel: "FAS2720",
    deviceAgeYears: 5.1,
    endOfLife: false,
    storageCapacityTB: 220,
    utilizationPct: 71,
    itBudgetUSD: 260_000,
    cloudStatus: "licensed_not_deployed",
    contractRenewalDays: 75,
    annualRevenue: 980_000_000,
    lastContactDate: "2026-05-02",
    pipelineStage: "not_contacted",
  },
  {
    id: "acc-10",
    accountName: "Quanta Semiconductor",
    salesRep: "Jordan Reyes",
    industry: "Tech",
    region: "APAC",
    companySize: "8,800 employees",
    deviceModel: "AFF A700",
    deviceAgeYears: 3.2,
    endOfLife: false,
    storageCapacityTB: 640,
    utilizationPct: 62,
    itBudgetUSD: 520_000,
    cloudStatus: "licensed_not_deployed",
    contractRenewalDays: 165,
    annualRevenue: 3_400_000_000,
    lastContactDate: "2026-04-10",
    pipelineStage: "contacted",
  },
  {
    id: "acc-11",
    accountName: "Orion Logistics Group",
    salesRep: "Marcus Wright",
    industry: "Manufacturing",
    region: "EMEA",
    companySize: "11,000 employees",
    deviceModel: "FAS8200",
    deviceAgeYears: 5.9,
    endOfLife: true,
    storageCapacityTB: 380,
    utilizationPct: 69,
    itBudgetUSD: 230_000,
    cloudStatus: "none",
    contractRenewalDays: 58,
    annualRevenue: 2_900_000_000,
    lastContactDate: null,
    pipelineStage: "not_contacted",
  },

  // ---------- COLD (5) ----------
  {
    id: "acc-12",
    accountName: "Cascade Public Utilities",
    salesRep: "Sofia Ramos",
    industry: "Government",
    region: "West",
    companySize: "5,600 employees",
    deviceModel: "FAS2720",
    deviceAgeYears: 6.5,
    endOfLife: true,
    storageCapacityTB: 180,
    utilizationPct: 58,
    itBudgetUSD: 180_000,
    cloudStatus: "none",
    contractRenewalDays: 95,
    annualRevenue: 620_000_000,
    lastContactDate: null,
    pipelineStage: "not_contacted",
  },
  {
    id: "acc-13",
    accountName: "Harbor City Schools",
    salesRep: "Sofia Ramos",
    industry: "Government",
    region: "East",
    companySize: "3,200 employees",
    deviceModel: "FAS2720",
    deviceAgeYears: 4.8,
    endOfLife: true,
    storageCapacityTB: 120,
    utilizationPct: 45,
    itBudgetUSD: 140_000,
    cloudStatus: "licensed_not_deployed",
    contractRenewalDays: 220,
    annualRevenue: 410_000_000,
    lastContactDate: "2026-03-20",
    pipelineStage: "contacted",
  },
  {
    id: "acc-14",
    accountName: "Summit Outdoor Retail",
    salesRep: "Sofia Ramos",
    industry: "Retail",
    region: "Central",
    companySize: "2,400 employees",
    deviceModel: "AFF A220",
    deviceAgeYears: 2.6,
    endOfLife: false,
    storageCapacityTB: 90,
    utilizationPct: 55,
    itBudgetUSD: 160_000,
    cloudStatus: "hybrid",
    contractRenewalDays: 300,
    annualRevenue: 520_000_000,
    lastContactDate: "2026-02-28",
    pipelineStage: "not_contacted",
  },
  {
    id: "acc-15",
    accountName: "Ironclad Defense Systems",
    salesRep: "Marcus Wright",
    industry: "Manufacturing",
    region: "East",
    companySize: "4,800 employees",
    deviceModel: "FAS2750",
    deviceAgeYears: 3.4,
    endOfLife: false,
    storageCapacityTB: 200,
    utilizationPct: 48,
    itBudgetUSD: 150_000,
    cloudStatus: "licensed_not_deployed",
    contractRenewalDays: 270,
    annualRevenue: 1_100_000_000,
    lastContactDate: "2026-03-05",
    pipelineStage: "not_contacted",
  },
  {
    id: "acc-16",
    accountName: "Lumen Media Holdings",
    salesRep: "Jordan Reyes",
    industry: "Tech",
    region: "EMEA",
    companySize: "1,800 employees",
    deviceModel: "FAS2720",
    deviceAgeYears: 2.2,
    endOfLife: true,
    storageCapacityTB: 140,
    utilizationPct: 52,
    itBudgetUSD: 120_000,
    cloudStatus: "none",
    contractRenewalDays: 400,
    annualRevenue: 360_000_000,
    lastContactDate: null,
    pipelineStage: "not_contacted",
  },

  // ---------- NOT READY (4) ----------
  {
    id: "acc-17",
    accountName: "Glacier Regional Co-op",
    salesRep: "Marcus Wright",
    industry: "Retail",
    region: "Central",
    companySize: "900 employees",
    deviceModel: "FAS2720",
    deviceAgeYears: 0.8,
    endOfLife: false,
    storageCapacityTB: 60,
    utilizationPct: 32,
    itBudgetUSD: 80_000,
    cloudStatus: "none",
    contractRenewalDays: 650,
    annualRevenue: 180_000_000,
    lastContactDate: null,
    pipelineStage: "not_contacted",
  },
  {
    id: "acc-18",
    accountName: "Riverstone County Gov",
    salesRep: "Sofia Ramos",
    industry: "Government",
    region: "Central",
    companySize: "1,400 employees",
    deviceModel: "FAS2720",
    deviceAgeYears: 1.4,
    endOfLife: false,
    storageCapacityTB: 80,
    utilizationPct: 38,
    itBudgetUSD: 95_000,
    cloudStatus: "none",
    contractRenewalDays: 540,
    annualRevenue: 240_000_000,
    lastContactDate: null,
    pipelineStage: "not_contacted",
  },
  {
    id: "acc-19",
    accountName: "Coral Bay Hospitality",
    salesRep: "Sofia Ramos",
    industry: "Retail",
    region: "APAC",
    companySize: "1,100 employees",
    deviceModel: "FAS2720",
    deviceAgeYears: 0.5,
    endOfLife: false,
    storageCapacityTB: 50,
    utilizationPct: 28,
    itBudgetUSD: 70_000,
    cloudStatus: "none",
    contractRenewalDays: 720,
    annualRevenue: 150_000_000,
    lastContactDate: null,
    pipelineStage: "not_contacted",
  },
  {
    id: "acc-20",
    accountName: "Pinecrest Public Library",
    salesRep: "Sofia Ramos",
    industry: "Government",
    region: "West",
    companySize: "400 employees",
    deviceModel: "FAS2720",
    deviceAgeYears: 0.9,
    endOfLife: false,
    storageCapacityTB: 30,
    utilizationPct: 35,
    itBudgetUSD: 60_000,
    cloudStatus: "none",
    contractRenewalDays: 600,
    annualRevenue: 80_000_000,
    lastContactDate: null,
    pipelineStage: "not_contacted",
  },
];
