/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RenewalsRouteImport } from './routes/renewals'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ImportsRouteImport } from './routes/imports'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ActionPlansRouteImport } from './routes/action-plans'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActionPlansIndexRouteImport } from './routes/action-plans.index'
import { Route as ActionPlansAccountIdRouteImport } from './routes/action-plans.$accountId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RenewalsRoute = RenewalsRouteImport.update({
  id: '/renewals',
  path: '/renewals',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportsRoute = ImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionPlansRoute = ActionPlansRouteImport.update({
  id: '/action-plans',
  path: '/action-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionPlansIndexRoute = ActionPlansIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ActionPlansRoute,
} as any)
const ActionPlansAccountIdRoute = ActionPlansAccountIdRouteImport.update({
  id: '/$accountId',
  path: '/$accountId',
  getParentRoute: () => ActionPlansRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/action-plans': typeof ActionPlansRouteWithChildren
  '/auth': typeof AuthRoute
  '/imports': typeof ImportsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/renewals': typeof RenewalsRoute
  '/settings': typeof SettingsRoute
  '/action-plans/$accountId': typeof ActionPlansAccountIdRoute
  '/action-plans/': typeof ActionPlansIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/auth': typeof AuthRoute
  '/imports': typeof ImportsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/renewals': typeof RenewalsRoute
  '/settings': typeof SettingsRoute
  '/action-plans/$accountId': typeof ActionPlansAccountIdRoute
  '/action-plans': typeof ActionPlansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/action-plans': typeof ActionPlansRouteWithChildren
  '/auth': typeof AuthRoute
  '/imports': typeof ImportsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/renewals': typeof RenewalsRoute
  '/settings': typeof SettingsRoute
  '/action-plans/$accountId': typeof ActionPlansAccountIdRoute
  '/action-plans/': typeof ActionPlansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/action-plans'
    | '/auth'
    | '/imports'
    | '/leaderboard'
    | '/renewals'
    | '/settings'
    | '/action-plans/$accountId'
    | '/action-plans/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/auth'
    | '/imports'
    | '/leaderboard'
    | '/renewals'
    | '/settings'
    | '/action-plans/$accountId'
    | '/action-plans'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/action-plans'
    | '/auth'
    | '/imports'
    | '/leaderboard'
    | '/renewals'
    | '/settings'
    | '/action-plans/$accountId'
    | '/action-plans/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  ActionPlansRoute: typeof ActionPlansRouteWithChildren
  AuthRoute: typeof AuthRoute
  ImportsRoute: typeof ImportsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  RenewalsRoute: typeof RenewalsRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renewals': {
      id: '/renewals'
      path: '/renewals'
      fullPath: '/renewals'
      preLoaderRoute: typeof RenewalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imports': {
      id: '/imports'
      path: '/imports'
      fullPath: '/imports'
      preLoaderRoute: typeof ImportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/action-plans': {
      id: '/action-plans'
      path: '/action-plans'
      fullPath: '/action-plans'
      preLoaderRoute: typeof ActionPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/action-plans/': {
      id: '/action-plans/'
      path: '/'
      fullPath: '/action-plans/'
      preLoaderRoute: typeof ActionPlansIndexRouteImport
      parentRoute: typeof ActionPlansRoute
    }
    '/action-plans/$accountId': {
      id: '/action-plans/$accountId'
      path: '/$accountId'
      fullPath: '/action-plans/$accountId'
      preLoaderRoute: typeof ActionPlansAccountIdRouteImport
      parentRoute: typeof ActionPlansRoute
    }
  }
}

interface ActionPlansRouteChildren {
  ActionPlansAccountIdRoute: typeof ActionPlansAccountIdRoute
  ActionPlansIndexRoute: typeof ActionPlansIndexRoute
}

const ActionPlansRouteChildren: ActionPlansRouteChildren = {
  ActionPlansAccountIdRoute: ActionPlansAccountIdRoute,
  ActionPlansIndexRoute: ActionPlansIndexRoute,
}

const ActionPlansRouteWithChildren = ActionPlansRoute._addFileChildren(
  ActionPlansRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  ActionPlansRoute: ActionPlansRouteWithChildren,
  AuthRoute: AuthRoute,
  ImportsRoute: ImportsRoute,
  LeaderboardRoute: LeaderboardRoute,
  RenewalsRoute: RenewalsRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
