/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RenewalsRouteImport } from './routes/renewals'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ImportsRouteImport } from './routes/imports'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ActionPlansRouteImport } from './routes/action-plans'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActionPlansIndexRouteImport } from './routes/action-plans.index'
import { Route as ActionPlansAccountIdRouteImport } from './routes/action-plans.$accountId'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RenewalsRoute = RenewalsRouteImport.update({
  id: '/renewals',
  path: '/renewals',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportsRoute = ImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionPlansRoute = ActionPlansRouteImport.update({
  id: '/action-plans',
  path: '/action-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionPlansIndexRoute = ActionPlansIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ActionPlansRoute,
} as any)
const ActionPlansAccountIdRoute = ActionPlansAccountIdRouteImport.update({
  id: '/$accountId',
  path: '/$accountId',
  getParentRoute: () => ActionPlansRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/action-plans': typeof ActionPlansRouteWithChildren
  '/auth': typeof AuthRoute
  '/imports': typeof ImportsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/mcp': typeof McpRoute
  '/renewals': typeof RenewalsRoute
  '/settings': typeof SettingsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/action-plans/$accountId': typeof ActionPlansAccountIdRoute
  '/action-plans/': typeof ActionPlansIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/auth': typeof AuthRoute
  '/imports': typeof ImportsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/mcp': typeof McpRoute
  '/renewals': typeof RenewalsRoute
  '/settings': typeof SettingsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/action-plans/$accountId': typeof ActionPlansAccountIdRoute
  '/action-plans': typeof ActionPlansIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/action-plans': typeof ActionPlansRouteWithChildren
  '/auth': typeof AuthRoute
  '/imports': typeof ImportsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/mcp': typeof McpRoute
  '/renewals': typeof RenewalsRoute
  '/settings': typeof SettingsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/action-plans/$accountId': typeof ActionPlansAccountIdRoute
  '/action-plans/': typeof ActionPlansIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/action-plans'
    | '/auth'
    | '/imports'
    | '/leaderboard'
    | '/mcp'
    | '/renewals'
    | '/settings'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/action-plans/$accountId'
    | '/action-plans/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/auth'
    | '/imports'
    | '/leaderboard'
    | '/mcp'
    | '/renewals'
    | '/settings'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/action-plans/$accountId'
    | '/action-plans'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/action-plans'
    | '/auth'
    | '/imports'
    | '/leaderboard'
    | '/mcp'
    | '/renewals'
    | '/settings'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/action-plans/$accountId'
    | '/action-plans/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  ActionPlansRoute: typeof ActionPlansRouteWithChildren
  AuthRoute: typeof AuthRoute
  ImportsRoute: typeof ImportsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  McpRoute: typeof McpRoute
  RenewalsRoute: typeof RenewalsRoute
  SettingsRoute: typeof SettingsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renewals': {
      id: '/renewals'
      path: '/renewals'
      fullPath: '/renewals'
      preLoaderRoute: typeof RenewalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imports': {
      id: '/imports'
      path: '/imports'
      fullPath: '/imports'
      preLoaderRoute: typeof ImportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/action-plans': {
      id: '/action-plans'
      path: '/action-plans'
      fullPath: '/action-plans'
      preLoaderRoute: typeof ActionPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/action-plans/': {
      id: '/action-plans/'
      path: '/'
      fullPath: '/action-plans/'
      preLoaderRoute: typeof ActionPlansIndexRouteImport
      parentRoute: typeof ActionPlansRoute
    }
    '/action-plans/$accountId': {
      id: '/action-plans/$accountId'
      path: '/$accountId'
      fullPath: '/action-plans/$accountId'
      preLoaderRoute: typeof ActionPlansAccountIdRouteImport
      parentRoute: typeof ActionPlansRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ActionPlansRouteChildren {
  ActionPlansAccountIdRoute: typeof ActionPlansAccountIdRoute
  ActionPlansIndexRoute: typeof ActionPlansIndexRoute
}

const ActionPlansRouteChildren: ActionPlansRouteChildren = {
  ActionPlansAccountIdRoute: ActionPlansAccountIdRoute,
  ActionPlansIndexRoute: ActionPlansIndexRoute,
}

const ActionPlansRouteWithChildren = ActionPlansRoute._addFileChildren(
  ActionPlansRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  ActionPlansRoute: ActionPlansRouteWithChildren,
  AuthRoute: AuthRoute,
  ImportsRoute: ImportsRoute,
  LeaderboardRoute: LeaderboardRoute,
  McpRoute: McpRoute,
  RenewalsRoute: RenewalsRoute,
  SettingsRoute: SettingsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
